### ISSUE TITLE
Issue with docker file when its running on ecs 

### ISSUE THREAD

**Issue by ghost** [advanced-security/probot-security-alerts#69]
d

**Comment by kenmuse** [comment]
To pass a value such as `PRIVATE_KEY` into the image you are building, you need to provide an `ARG` with the same name. At build time, you can't set an environment variable except through a `--build-arg`.  Docker has a deep dive into this process [in their docs](https://docs.docker.com/build/building/variables/). That said, I would not recommend this approach since it embeds the values of the secrets into your layers, making them insecure.

Instead, you could remove that line and the `WEBHOOK_SECRET`. Then use the command line `--env WEBHOOK_SECRET=.... --env PRIVATE_KEY` ([docs](https://docs.docker.com/reference/cli/docker/container/run/#env)) to pass the values in to the container when it starts. The most secure way to do that on AWS is to use Secrets Manager with a container definition. This process is covered in the [AWS docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/secrets-envvar-secrets-manager.html). 

Hopefully that should unblock you. I'm working on a new version of the code that should hopefully make it easier to deploy on AWS Lambda and Azure Functions.
